### ISSUE TITLE
Manage user account and additional personal information mapping

### ISSUE THREAD

**Issue by kenhys** [okkez/pragmatic-bot#1]
# What is problem?

pragmatic-bot only supports GitHub, so we can't track other activity correctly.
It makes better if we can associate GitHub account and personal information such as E-mail address or user name which is enough information to determine who he/she is:

```
kenhys -> association -> hayashi@clear-code.com or "Kentaro Hayashi"
```

# What is expected?

We can write other contribution module and easily unify personal activities into statistics data.

# How to fix the problem?

T.B.D. We need to define spec to unify account information.

* How to store information?
  * email: multiple E-mail is used?
  * user name: First Name/Family Name or nick name or something else
* How to resolve id unification?
  * contribution module use specific API to resolve personal information to GitHub ID:

**Comment by okkez** [comment]
I've added new feature to register URL.
