### ISSUE TITLE
Feedback::Github sorts but Feedback::URL doesn't sort

### ISSUE THREAD

**Issue by kou** [okkez/pragmatic-bot#5]
`Feedback::Github`: https://github.com/okkez/pragmatic-bot/blob/master/lib/ruboty/actions/github.rb#L99

```ruby
 new_content = (content.lines + [line]).sort.join
```

`Feedback::URL`: https://github.com/okkez/pragmatic-bot/blob/master/lib/ruboty/handlers/feedback/url.rb#L48

```ruby
 content + line)
```

**Comment by okkez** [comment]
Fixed
